name: CI

on: 
  push:
    branches:
      - main

jobs:
  test-automatico:
    name: 'Jest test'
    runs-on: ubuntu-latest

    steps:
      - name: Echo eh message
        run: |
          echo "Hola mundo!"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
